[global_env]
GLOBAL_VAR1 = global_var1_is_set

[global_cfg]

[prediction_api]
ENTITY = mroha_test
HELPER = mroha_iflow_doa
#CORES_CONFIDENCE = 85 
#MEMORY_CONFIDENCE = 85 
#RUNTIME_CONFIDENCE = 85 
#RUNTIME_MULTIPLIER = 1000:3000
#NB_DELAY = 0
#DELETE_PREDICTION_EXIT_STATUS = 10

[echo_test]
RUNDIR = $WORKAREA
CMD = echo $GLOBAL_VAR1

[perl_test]
RUNDIR = $WORKAREA
CMD = ${WORKAREA}/iflow/perl_test.pl
DEPS = echo_test

[root_job]
RUNDIR = $WORKAREA
CMD = sleep 10 && (/usr/bin/env > $WORKAREA/env.dump)
DEPS = perl_test

[passing_branch_A_job1]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = root_job

[passing_branch_B_job1]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = root_job

[failing_branch_job1_pass]
RUNDIR = $WORKAREA
CMD = sleep 10 
DEPS = root_job

[passing_branch_A_job2]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_A_job1

[passing_branch_B_job2]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_B_job1

[failing_branch_job2_force_pass]
RUNDIR = $WORKAREA
CMD = slep 10 || /bin/true
DEPS = failing_branch_job1_pass

[passing_branch_A_job3]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_A_job2

[passing_branch_B_job3]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_B_job2

[passing_branch_C_from_job3]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_A_job3 passing_branch_B_job3

[failing_branch_job3_badcmd]
RUNDIR = $WORKAREA
CMD = slep 10
DEPS = failing_branch_job2_force_pass
GATING=0

[passing_branch_A_job4]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_A_job3

[passing_branch_C_job_4]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_C_from_job3

[failing_branch_job4_pass]
RUNDIR = $WORKAREA
CMD = sleep 10 
DEPS = failing_branch_job3_badcmd

[passing_branch_A_job5]
RUNDIR = $WORKAREA
CMD = sleep 10
DEPS = passing_branch_A_job4

[failing_branch_job5_pass]
RUNDIR = $WORKAREA
CMD = sleep 10 
DEPS = failing_branch_job4_pass
