# Package partitions,  then package icm_top

# Partition packaging.
# BLOCK variable required for package flow to parse the blocks.cfg
[parh2bpkg]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make package DUT=icm TOP_MODULE_NAME=<block> PASS=<block> BLOCK=<block> PACKAGE_CFG_FILE=package.cfg

# ICM PIP packaging. Partitions are stubs 
[h2bpkg_icm]
GSPOST  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make package DUT=icm TOP_MODULE_NAME=icm_top PASS=icm_top BLOCK=icm_top PACKAGE_CFG_FILE=package.cfg

# Disable reading partition UPF for icm_top
[fix_upf_for_pip]
GSPOST = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make fix_upf_for_pip DUT=icm TOP_MODULE_NAME=icm_top PASS=icm_top
DEPS   = h2bpkg_icm
