# ICM h2b. Using GSPRE=true to launch before par runs

[vcs4h2b_icm]
GSPRE  = true
RUNDIR = $WORKAREA/verif/vcs
CMD    = /usr/bin/make vcs4h2b DUT=icm PASS=vcs4h2b CONFIG=vcs4h2b.flow.cfg

[fullchipdump_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make fullchipdump DUT=icm
DEPS   = vcs4h2b_icm

[v2k_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make v2k_config DUT=icm
DEPS   = fullchipdump_icm

[hip_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make hip DUT=icm
DEPS   = v2k_icm

[sip_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make sip DUT=icm
DEPS   = hip_icm

[sochier_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make soc_hier DUT=icm
DEPS   = sip_icm

[fixndm_icm]
GSPRE  = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make fixndm DUT=icm PASS=icm_top
DEPS   = hip_icm


# ICM Partition Runs  (using iflow in h2b mode)

[parfullchipdump]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make fullchipdump DUT=icm TOP_MODULE_NAME=<block> PASS=<block>

[parv2k]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make v2k_config DUT=icm TOP_MODULE_NAME=<block> PASS=<block>
DEPS   = parfullchipdump

[parhip]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make hip DUT=icm TOP_MODULE_NAME=<block> PASS=<block>
DEPS   = parv2k

[parsip]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make sip DUT=icm TOP_MODULE_NAME=<block> PASS=<block>
DEPS   = parhip

[parfixndm]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make fixndm DUT=icm TOP_MODULE_NAME=<block> PASS=<block>
DEPS   = parhip

[parsignoffv2k]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make v2k_config DUT=icm TOP_MODULE_NAME=<block> PASS=<block> CONFIG=signoff.flow.cfg
DEPS   = parsip

[parsignoffsip]
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make sip DUT=icm TOP_MODULE_NAME=<block> PASS=<block> CONFIG=signoff.flow.cfg
DEPS   = parsignoffv2k


# Partition in Partition runs for stub filelist
# This collateral is placed in $WORKAREA/output/DUT/partition
[v2k_icm_pip]
GSPOST = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make v2k_config DUT=icm CONFIG=pip.flow.cfg

[sip_icm_pip]
GSPOST = true
RUNDIR = $WORKAREA/handoff/h2b
CMD    = /usr/bin/make sip DUT=icm CONFIG=pip.flow.cfg
DEPS   = v2k_icm_pip
