##############Template override.ini file######################
### This override file is NOT intended to work as is and must be edited to work for a given IP

#ATTENTION: CHANGE/FIX VALUES HERE
#Set the following to be used for substitution in other keys
#For example: The alias given below is used for cxlcm. Please change this according to your own IP.
#alias = cxlcm_host_top,cxlcm_host,cxlcm_host_par
alias = alu

##Following keys are accessed by rules across categories
cheetah1 = False
cheetah2 = True
ipsoc = False


#[Build___Run]
iptype = sip
vcscompiledir = [model_root]/output/[dut]/vcs/*/vcs_compile/
topvcscompilelog = [dut].compile.log
vcssim_model_names = [dut]
vcssim_elabdir = [model_root]/output/[dut]/vcssim
vcssim_elablogfile = elab.log
ufe = False
rtlrptdir = [model_root]/tools/reports
acevcslogfile = [alias]_vcs.log
vcselablogdir = [model_root]/output/[dut]/vcs/*/vcs_elab/
vcselablogfile = elab.log
iproot = [model_root]

#[CDC]
cdcdir = [model_root]/collaterals/sgcdc/[dut]/
cdcdirspyglass = [model_root]/collaterals/sgcdc/[dut]/
rdcdirspyglass = [model_root]/collaterals/sgrdc/[dut]/
cdctopfile = cdc_hier_ctrl_[alias].v
cdcquesta = False
cdcquestacfm = False
cdcquestahdm = False
cdcspyglass = True
cdclintviolationsfilespyglass = [model_root]/collaterals/sgcdc/[dut]/*_cdc_verify_struct.run_cdc_verify_struct_violations_sgcdc.xml
rdclintviolationsfilespyglass = [model_root]/collaterals/sgrdc/[dut]/*_rdc_verify_struct.run_rdc_verify_struct_violations_sgcdc.xml

#[Collage]
ipxactsearchdir = [model_root]/collaterals/collage/[dut]/ipxact/*/2014/
topmodulename = alu
collagedir = [model_root]/collaterals/collage/[dut]/reports
collagesumrptfile = *.build.summary
collagewarnrptfile = *.build.warning

#[DFt]
sgdftsummaryfile = [model_root]/output/[dut]/sgdft/[alias]/dft_run/ipds_dft_sgdft.summary
atpgsummaryfile = [model_root]/output/[dut]/atpg/*/atpg_run/sage/WORK/*/reports/*ipds_dft_atpg.summary
synsummaryfile = [model_root]/collaterals/dc/[dut]/reports/*ipds*summary

#[Documentation]
docdir = [model_root]/doc

#[Emulation_FPGA]
emuldir = [model_root]/collaterals/effm*/[dut]/
emullog = emul_build_soc_status.log
emulfpgalog = CHECK_FPGA.log
effmstatuslog = effm_status.log
emulzselog = CHECK_ZSE.log

#[FEV]

lecundrptfile = [model_root]/collaterals/lec/[dut]/[alias].zmapped.rpt
lecrptfile = [model_root]/collaterals/lec/[dut]/[alias].summary.rpt
lecdir=[model_root]/collaterals/lec/[dut]
#ATTENTION: CHANGE/FIX VALUES HERE
#lectask needs to be set to rtl2nl for signoff, but if the IPs are running fev_lite, this key can be set to fev_lite
lectask=rtl2nl
topblockname=[alias]

#[MCP_FP]
#ATTENTION: CHANGE/FIX VALUES HERE
#the following path has the process directory (CICG74) in it as seen in CXLCM, if the process directory is different or not present, then please adjust this path appropriately
fishtailreport = [model_root]/output/[dut]/fishtail/PIC/fishtail_run/audit_report/*.ft_audit.rpt

#[Phys_Design_Enabling]
#rdtsynsummaryfile = [model_root]/output/[dut]/fc/*/synth_run/report/*.ipds.summary
mastersdc = [alias]_[dut].sdc
ipreleasepath = [model_root]/collaterals/sdc/[dut]/
synduetsummaryfile = [model_root]/collaterals/caliber/[dut]/reports/*.summary

#[Power_Intent]
vclpoutputdir = [model_root]/output/[dut]/vclp/
sglp = False
vclp = True
vclpdir = [model_root]/output/[dut]/vclp/*/vclp_run
vcstsessionlogdir = [model_root]/output/[dut]/vclp/*/vclp_run

#[RDL]
rdlfusetop = [alias]_fuse_top
rdlsearchpath = [model_root]/tools/srdl
rdlfusesearchpath = 
nebuloncheckerxmlfile = [model_root]/tools/nebulon/output/nebulon_[alias]_violations.xml
rdlqtchcrsearchpath = [model_root]/tb/verif/output/qualitychecker
rdlvsrtlcrcheckerfile = [alias]_rdlvsrtl_summary.txt
rdlvsrtlcrsearchpath = [model_root]/tools/srdl/common
crifvsrtlcrcheckerfile = [alias]_crifvsrtl_summary.txt
rdltapfile = tap.rdl
rdltapsearchpath = [model_root]/tools/srdl/tap/srdl
osxmlsearchpath = [model_root]/tools/osxml
osxmlrootpath = 

#[RTL_Lint]
spyglasslintxmlfile = spyglass_violations_report.xml
spyglasslintdir = [model_root]/collaterals/sglint/[dut]/reports/
rtllintlintra = False
rtllintspyglass = True
globaldirs = 
spyglasslintrulesconfig = spyglass_rules_report.xml
spyglassopenlatchdir = [model_root]/collaterals/sgol/[dut]/reports/
spyglassopenlatchxmlfile = spyglass_violations_report.xml

#[Review]

#[SV_TB]

#[Security]
#docdir = [model_root]/doc

#[Simulation]

#[VISA]
visalintviolxml = [model_root]/output/[dut]/visa/*/visa_run/*.visa.lint.out.xml

