[Config]
# Netbatch
nbqueue         = /DCG/MountMorgan/SD
nbpool          = zsc7_normal
nbclass         = SLES12SP5&&64G

# Common stack vars
FE_WORKAREA     = $WORKAREA
SRC             = runs

# Default settings
keep_workarea   = 1
psetup_force    = 1
setup_r2g_force = 1
