[Includes]
$WORKAREA/handoff/r2g/default.ini

[Config]
# Tech
project_scope = pesg/2021.09
cfg           = n5_h210_m15.cth
tech          = h210_snps_m15
FE_TECH       = n5

# Work area
FE_COLLATERAL = $WORKAREA/output/alu2/h2b/trial/CTHBE/fe_collateral
stack_file = $WORKAREA/handoff/r2g/stack_files/apr_fc_import_design.stack
top_task_name = alu2.n5.taskfile
block = alu2 
ward_id = n5.ward1
workarea = $WORKAREA/output/alu2/r2g
top_task_area = $WORKAREA/output/alu2/r2g
