"""Render the CSV plan, replay script, summary and log."""

from __future__ import annotations

import csv
import io
import shlex
import shutil
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from cthrepo_to_zenws.gitdiff import extract_tree
from cthrepo_to_zenws.plan import (
    AUTO_BUCKETS,
    BUCKET_AUTO_ADD,
    BUCKET_AUTO_DELETE,
    BUCKET_AUTO_RENAME,
    BUCKET_AUTO_UPDATE,
    BUCKET_MANUAL_LOCATE,
    BUCKET_MANUAL_MERGE,
    BUCKET_MANUAL_RENAME,
    BUCKET_ORDER,
    BUCKET_REVIEW_ADD,
    BUCKET_REVIEW_COMMENT_ONLY,
    BUCKET_REVIEW_DELETE,
    BUCKET_REVIEW_WHITESPACE_ONLY,
    BUCKET_SKIP_IGNORED,
    BUCKET_SKIP_NOT_MIGRATED,
    BUCKET_SKIP_UP_TO_DATE,
    NO_ACTION_BUCKETS,
    PlanRow,
)

OUTPUT_PREFIX = "cthrepo-to-zenws"
REVIEW_SRC_DIRNAME = f"{OUTPUT_PREFIX}.review-src"
CSV_HEADER = [
    "filename",
    "cheetah_source_path",
    "change",
    "resolution_rule",
    "action_bucket",
    "zen_destination_path",
    "zen_previous_path",
    "notes",
]
TIME_FORMAT = "%Y-%m-%d %H:%M:%S %Z"

BUCKET_MEANING = {
    BUCKET_AUTO_ADD: "new upstream file, trusted destination, nothing there yet - replayed",
    BUCKET_AUTO_UPDATE: "zen copy still byte-identical to the base tag - replayed",
    BUCKET_AUTO_DELETE: "zen copy still byte-identical to the base tag - replayed",
    BUCKET_AUTO_RENAME: "both endpoints resolve, old copy untouched, new slot free - replayed",
    BUCKET_REVIEW_ADD: "new upstream file, but the destination was inferred by a heuristic",
    BUCKET_REVIEW_COMMENT_ONLY: "zen copy diverged; the upstream change is comments only",
    BUCKET_REVIEW_WHITESPACE_ONLY: "zen copy diverged; the upstream change is whitespace only",
    BUCKET_REVIEW_DELETE: "deleted upstream, but the zen copy has local edits",
    BUCKET_MANUAL_MERGE: "zen copy diverged and the upstream change is real code, "
    "or the destination is already occupied",
    BUCKET_MANUAL_RENAME: "renamed upstream, but the old zen copy diverged "
    "or the new path has no destination",
    BUCKET_MANUAL_LOCATE: "no destination could be derived - the file has no home "
    "in the workspace",
    BUCKET_SKIP_UP_TO_DATE: "zen copy already matches the head tag - nothing to do",
    BUCKET_SKIP_IGNORED: "matched an --ignore pattern",
    BUCKET_SKIP_NOT_MIGRATED: "deleted upstream and never migrated into the workspace",
}


@dataclass
class RunInfo:
    command_line: str
    cheetah_repo: Path
    zenws_repo: Path
    dest_root: Path
    base_tag: str
    head_tag: str
    diff_command: list[str]
    report_path: Path | None
    mapping_entries: int
    category_rules: int
    start_epoch: float
    end_epoch: float = 0.0

    @property
    def elapsed(self) -> float:
        return self.end_epoch - self.start_epoch


def csv_filename(started: float) -> str:
    stamp = time.strftime("%Y-%m-%d_%H-%M-%S", time.localtime(started))
    return f"{OUTPUT_PREFIX}.csv.{stamp}"


def render_csv(rows: list[PlanRow]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(CSV_HEADER)
    for row in rows:
        writer.writerow(
            [
                row.filename,
                row.cheetah_path,
                row.change,
                row.resolution,
                row.bucket,
                row.csv_zen_path(),
                row.old_zen_path or "",
                row.notes,
            ]
        )
    return buffer.getvalue()


def bucket_counts(rows: list[PlanRow]) -> list[tuple[str, int]]:
    counts = Counter(row.bucket for row in rows)
    return [(bucket, counts[bucket]) for bucket in BUCKET_ORDER if counts[bucket]]


def render_replay(rows: list[PlanRow], info: RunInfo) -> str:
    q = shlex.quote
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by {OUTPUT_PREFIX}",
        f"# {info.command_line}",
        "#",
        "# Graft "
        f"{info.cheetah_repo} {info.base_tag}..{info.head_tag} -> {info.dest_root}",
        "#",
        "# Uncommented lines are safe automatic actions. Every TODO line needs a human.",
        "set -euo pipefail",
        "",
        f"CHEETAH_REPO={q(str(info.cheetah_repo))}",
        f"ZEN_DEST={q(str(info.dest_root))}",
        f"HEAD_TAG={q(info.head_tag)}",
        "",
        "graft() {",
        '  local src="$1" dst="$2"',
        '  mkdir -p "$ZEN_DEST/$(dirname "$dst")"',
        '  git -C "$CHEETAH_REPO" show "$HEAD_TAG:$src" > "$ZEN_DEST/$dst"',
        '  echo "grafted $dst"',
        "}",
        "",
        "drop() {",
        '  local dst="$1"',
        '  rm -f "$ZEN_DEST/$dst"',
        '  echo "removed $dst"',
        "}",
        "",
    ]

    for bucket in BUCKET_ORDER:
        bucket_rows = [row for row in rows if row.bucket == bucket]
        if not bucket_rows:
            continue
        lines.append(f"# ---- {bucket} ({len(bucket_rows)}) ----")
        for row in bucket_rows:
            if bucket in NO_ACTION_BUCKETS:
                lines.append(f"# {row.cheetah_path}: {row.notes}")
                continue
            dest = row.zen_path or "UNRESOLVED"
            if row.change == "delete":
                actions = [f"drop {q(dest)}"]
            elif row.change == "rename":
                actions = [f"graft {q(row.cheetah_path)} {q(dest)}"]
                if row.old_zen_path and row.old_zen_path != dest:
                    actions.append(f"drop {q(row.old_zen_path)}")
            else:
                actions = [f"graft {q(row.cheetah_path)} {q(dest)}"]
            if bucket in AUTO_BUCKETS:
                lines += actions
            else:
                lines.append(f"# TODO({bucket}) {row.notes}")
                lines += [f"# {action}" for action in actions]
        lines.append("")

    lines.append('echo "replay complete"')
    lines.append("")
    return "\n".join(lines)


def review_dest(row: PlanRow) -> str | None:
    """The zen file a reviewer opens: for a rename that is still the old copy."""
    if row.change == "rename":
        return row.old_zen_path or row.zen_path
    return row.zen_path


def review_sources(rows: list[PlanRow]) -> list[str]:
    """Cheetah paths that must be materialised at the head tag for the review file."""
    return sorted(
        {
            row.cheetah_path
            for row in rows
            if row.bucket not in NO_ACTION_BUCKETS and row.change != "delete"
        }
    )


def render_replay_review(rows: list[PlanRow], info: RunInfo, src_root: Path) -> str:
    """Same buckets and same order as the replay, as cut-and-paste meld commands."""
    q = shlex.quote
    lines = [
        f"# {OUTPUT_PREFIX} visual review",
        f"# {info.command_line}",
        "#",
        f"# Cheetah {info.head_tag} sources staged under {src_root}",
        f"# Zen destinations under {info.dest_root}",
        "#",
        "# Same buckets and same order as the .replay. Copy any line and run it.",
        "# Commented lines have nothing to diff; the reason follows the command.",
        "",
    ]

    for bucket in BUCKET_ORDER:
        bucket_rows = [row for row in rows if row.bucket == bucket]
        if not bucket_rows:
            continue
        lines.append(f"# ---- {bucket} ({len(bucket_rows)}) ----")
        for row in bucket_rows:
            if bucket in NO_ACTION_BUCKETS:
                lines.append(f"# {row.cheetah_path}: {row.notes}")
                continue

            dest = review_dest(row)
            src = q(str(src_root / row.cheetah_path))
            if dest is None:
                lines.append(f"# meld {src} ? # no destination resolved")
                continue

            abs_dest = info.dest_root / dest
            if row.change == "delete":
                lines.append(f"# meld {q(str(abs_dest))} # deleted upstream, no source to compare")
            elif abs_dest.exists():
                lines.append(f"meld {src} {q(str(abs_dest))}")
            else:
                lines.append(f"# meld {src} {q(str(abs_dest))} # destination does not exist yet")
        lines.append("")

    return "\n".join(lines)


def render_summary(rows: list[PlanRow], info: RunInfo) -> str:
    counts = bucket_counts(rows)
    automatable = sum(n for bucket, n in counts if bucket in AUTO_BUCKETS)
    no_action = sum(n for bucket, n in counts if bucket in NO_ACTION_BUCKETS)
    needs_human = len(rows) - automatable - no_action

    lines = [
        f"{OUTPUT_PREFIX} summary",
        "=" * 60,
        f"command line      : {info.command_line}",
        f"start time        : {time.strftime(TIME_FORMAT, time.localtime(info.start_epoch))}",
        f"end time          : {time.strftime(TIME_FORMAT, time.localtime(info.end_epoch))}",
        f"start epoch       : {info.start_epoch:.6f}",
        f"end epoch         : {info.end_epoch:.6f}",
        f"elapsed seconds   : {info.elapsed:.3f}",
        "",
        f"cheetah repo      : {info.cheetah_repo}",
        f"base tag          : {info.base_tag}",
        f"head tag          : {info.head_tag}",
        f"diff command      : git -C {info.cheetah_repo} {' '.join(info.diff_command)}",
        f"zen workspace     : {info.zenws_repo}",
        f"zen dest root     : {info.dest_root}",
        f"migration report  : {info.report_path or '(none)'}",
        f"mapping entries   : {info.mapping_entries}",
        f"category rules    : {info.category_rules}",
        "",
        f"files in diff     : {len(rows)}",
        f"automatable       : {automatable}",
        f"needs review/merge: {needs_human}",
        f"no action         : {no_action}",
        "",
        "-- action buckets --",
    ]
    width = max((len(bucket) for bucket, _ in counts), default=0)
    lines += [f"  {bucket.ljust(width)} : {n}" for bucket, n in counts]

    lines.append("")
    lines.append("-- what each action bucket means --")
    for bucket, _ in counts:
        lines.append(f"  {bucket.ljust(width)} : {BUCKET_MEANING[bucket]}")

    for bucket, _ in counts:
        lines.append("")
        lines.append(f"-- {bucket} --")
        for row in rows:
            if row.bucket == bucket:
                dest = row.csv_zen_path() or "-"
                origin = f" (was {row.old_zen_path})" if row.old_zen_path else ""
                lines.append(
                    f"  [{row.change}] {row.cheetah_path} -> {dest}{origin}"
                    f"  ({row.resolution}; {row.notes})"
                )

    lines.append("")
    return "\n".join(lines)


def render_log(rows: list[PlanRow], info: RunInfo, debug: int) -> str:
    lines = [
        f"{OUTPUT_PREFIX} log (debug={debug})",
        f"command line: {info.command_line}",
        f"start: {time.strftime(TIME_FORMAT, time.localtime(info.start_epoch))} "
        f"({info.start_epoch:.6f})",
        f"end:   {time.strftime(TIME_FORMAT, time.localtime(info.end_epoch))} "
        f"({info.end_epoch:.6f})",
        f"diff:  git -C {info.cheetah_repo} {' '.join(info.diff_command)}",
        "",
    ]
    if debug >= 1:
        lines.append("-- bucket counts --")
        lines += [f"  {bucket}: {n}" for bucket, n in bucket_counts(rows)]
        lines.append("")
    if debug >= 3:
        lines.append("-- per-file decisions --")
        lines += [
            f"  {row.change:6} {row.resolution:20} {row.bucket:26} "
            f"{row.cheetah_path} -> {row.csv_zen_path() or '-'}"
            for row in rows
        ]
        lines.append("")
    if debug >= 5:
        lines.append("-- notes --")
        lines += [f"  {row.cheetah_path}: {row.notes}" for row in rows]
        lines.append("")
    return "\n".join(lines)


def write_outputs(
    outdir: Path, rows: list[PlanRow], info: RunInfo, debug: int, force: bool
) -> list[Path]:
    src_root = outdir / REVIEW_SRC_DIRNAME
    targets = {
        outdir / f"{OUTPUT_PREFIX}.replay": render_replay(rows, info),
        outdir / f"{OUTPUT_PREFIX}.replay.review": render_replay_review(rows, info, src_root),
        outdir / f"{OUTPUT_PREFIX}.summary": render_summary(rows, info),
        outdir / csv_filename(info.start_epoch): render_csv(rows),
    }
    if debug:
        targets[outdir / f"{OUTPUT_PREFIX}.log"] = render_log(rows, info, debug)

    if not force:
        clashes = [p for p in (*targets, src_root) if p.exists()]
        if clashes:
            names = ", ".join(p.name for p in clashes)
            raise FileExistsError(f"refusing to overwrite {names} (use --force)")

    for path, text in targets.items():
        path.write_text(text, encoding="utf-8")
    (outdir / f"{OUTPUT_PREFIX}.replay").chmod(0o755)

    shutil.rmtree(src_root, ignore_errors=True)
    extract_tree(info.cheetah_repo, info.head_tag, review_sources(rows), src_root)
    return sorted(targets)
