#!/usr/bin/perl -w
use strict;




my $WORK = $ENV{WORK};

my $CDSLIB = $ENV{CDSLIB};

my $DBB = $ENV{DBB};

my $fubname = &get_fubname($DBB);

my ($netlist_log_timestamp,$netlist_log_filepath) = &get_netlist_logfile($WORK,$fubname);

my %netlist_libs = &get_netlist_libs($netlist_log_filepath);

my %CDS_libs = &get_CDSLIB_libs($CDSLIB);

&compare_libs(\%netlist_libs,\%CDS_libs);

(my $lib_format_length, my $tag_format_length) = &get_format(\%netlist_libs);

print "\n\nLibrary report for fub: $fubname\n";
print "Netlist log file used: $netlist_log_filepath\n";
#print "Date and time logfile was compiled:  ";
print "Number of libraries referenced during netlist build: ", scalar (keys %netlist_libs), "\n\n";

foreach (sort keys %netlist_libs) {
    printf "library: %-${lib_format_length}s      tag: %-${tag_format_length}s\n", "$_", "$netlist_libs{$_}";
}

print "\n\n";


sub get_fubname {
    my $dbb = shift;
    if ($dbb =~ /[:]+/) {
        print "\n\$DBB contains more than one library name. ($DBB) \n";
        print "Please enter fub name:\n";
        chomp(my $in = <STDIN>);
        $in =~ s/(\w+)/\L$1/i;
        $in;
    }
    else {
        $dbb;
    }
}


sub get_netlist_logfile {
    my ($workpath,$cell) = @_;
    my @all_cdba_logfiles = glob "$workpath/netlists/${cell}__cdba_to_*.log";
    die "Could not find netlister logfiles for \"$cell\"\n" if (! defined($all_cdba_logfiles[0]));
    my %time_file;
    foreach (@all_cdba_logfiles) {
        $time_file{(stat($_))[9]} = "$_";
    }
    my $newest_time = (sort (keys %time_file))[-1];
    my $newest_file = $time_file{$newest_time};
    my @return_values = ($newest_time, $newest_file);
}


sub get_netlist_libs {
    my $logfile = shift;
    my %libs_warn;
    open (LOG, "$logfile") or die "could not open nike netlister logfile";
    while (<LOG>) {
        chomp;
        $libs_warn{$1} = "Library $1 not found in CDSLIB" if (/Building Cell: \w+, library:  (\S+),/);
    }
    close LOG;
    %libs_warn;
}

sub get_CDSLIB_libs {
    my $cdslib = shift;
    my %cdslib_info;
    open (CDS, "$cdslib") or die "could not open cdslib";    
    while (<CDS>) {
        chomp;
        $cdslib_info{$2} = "$1" if (/^DEFINE.*?\/([\w\.?]+)\/(\w+)$/);
    }
    close CDS;
    %cdslib_info;
}

sub compare_libs {
    my ($net_ref,$cds_ref) = @_;
    foreach my $net (keys %{$net_ref}) {
        if (exists $cds_ref->{$net}) {
            $net_ref->{$net} = $cds_ref->{$net};
        }
    }
}


sub get_format {
    my $net_ref = shift;
    my ($lib_length, $tag_length) = (0,0);
    foreach (keys %{$net_ref}) {
        $lib_length = length($_) if $lib_length < length($_);
        $tag_length = length($net_ref->{$_}) if $tag_length < length($net_ref->{$_});
    }
    ($lib_length,$tag_length);
}
